### ISSUE TITLE
デプロイ周りの改善

### ISSUE THREAD

**Issue by kaave** [framelunch/scaffold-wordpress#9]
## 詳細

10/16の週令で @supertaihei02  より指摘
詳細は申し訳ないですが忘れてしまったので雑にまとめますが、
要するにデプロイの際の作業がエレガントではないのでエレガントにしたい、とのこと

## ゴール

エレガント化

## 期日

なるはや

**Comment by nkenji09** [comment]
@supertaihei02 
すみません。その日動物病院でミーティング参加できなくて。。。
詳細を教えてもらえると助かります。

**Comment by nkenji09** [comment]
コンテナ内のWordpressメインファイルを
デプロイする方法を用意すべきではないか
っていう話。

Wordpressのメインファイルについてはどんどん更新されていくから
別に同じにしなくていいやーって思っていたけど
まぁ確かに開発段階でそれが原因でエラーとか出ちゃうとハマるから
デプロイできるようにしてみようと思う。

**Comment by nkenji09** [comment]
wordmoveを最初のDockerコンテナイメージにインストール済みの状態にしておきました。
.envファイルに環境情報を入力後 `make gen-movefile` すると自動的にMovefileを生成します。
(設定ファイルがあちこちに散らばるのがイヤだったので)

Movefileがある状態で `make prd-pull-db` とかやると本番環境のDB情報をLocalに入れられます。
ただし、本番環境がwordmoveのシステム要件に合わないケースも考えられるので
今まで通りDumpファイルをベースにDBの同期を行う方法も残しておきました。

ちょっとちょうどいい環境がなかったから、まだFTPでファイルをpullしておくテストしかしてないから
ポロポロ不具合出るだろうけど、見つけ次第潰します。
というわけで、一旦クローズ。
